version: '3.8'
services:
    laravel:
        build:
            context: ./laravel
            dockerfile: Dockerfile
        container_name: laravel
        tty: true
        #restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./laravel/:/var/www:cached
            - ./laravel/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            #- ./laravel/supervisord.conf:/etc/supervisord.conf
            #- ~/.ssh:/root/.ssh
        #command: sh -c "tail -f /dev/null && composer install"
  
        networks:
            - private
    server:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
           # - 443:443
        volumes:
            - ./laravel/:/var/www:delegated
            - ./laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
            #- ./laravel/ssl:/etc/nginx/conf.d/ssl
        networks:
            - private
        depends_on:
            - laravel    
    angular-app:
        build: 
            context: .
            dockerfile: ./angular/Dockerfile
        working_dir: /app
        container_name: angular
        ports:
            - 4200:4200
        volumes:
            - ./angular/:/app
        #command: npm install && ng serve --host 0.0.0.0 --port 4200
        command: sh -c "npm install && ng serve --host 0.0.0.0 --port 4200 --poll 1000"

       # command: ng serve --host 0.0.0.0 --port 4200
        networks:
            - private
    mysql:
        image: mysql:latest
        container_name: "mysql"
        tty: true
        environment:
            MYSQL_USER: muhammad
            MYSQL_PASSWORD: muhammad
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: muhammad
            MYSQL_ROOT_HOST: '%'
            SERVICE_NAME: mysql
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - private

    # PHPMYADMIN Service
    phpmyadmin:
        image: phpmyadmin
        container_name: "phpmyadmin"
        ports:
            - "7000:80"
        depends_on:
            - mysql
        environment:
            MYSQL_USER: muhammad
            MYSQL_PASSWORD: muhammad
            MYSQL_ROOT_PASSWORD: muhammad
            MYSQL_ROOT_HOST: '%'
            PMA_HOST: mysql
        networks:
            - private        

networks:
    private:
        driver: bridge
volumes:
    mysql-data:         
